using UnityEngine;
using TMPro;
using Unity.Mathematics;

public class GameObjects : MonoBehaviour
{
    private TextMeshProUGUI displayText;
    // Start is called once before the first execution of Update after the MonoBehaviour is created
    void Start()
    {
        displayText = GetComponent<TextMeshProUGUI>();
    }

    // Update is called once per frame
    void Update()
    {

    }

    public void GenerateFish()
    {
        Fish testFish = new Fish();
        testFish.Length = UnityEngine.Random.Range(1, 195);
        switch (testFish.Archetype) //Decided to use Switch statement for scalability and to keep a reasonable weight range for the length of the fish. Takes the archetype generated by length and puts out reasonable weight range
        {
            case "Small":
                testFish.Weight = UnityEngine.Random.Range(1, 50);
                break;
            case "Medium":
                testFish.Weight = UnityEngine.Random.Range(50, 95);
                break;
            case "Large":
                testFish.Weight = UnityEngine.Random.Range(96, 145);
                break;
            case "Extra Large":
                testFish.Weight = UnityEngine.Random.Range(146, 250);
                break;
        }
        testFish.Agression = UnityEngine.Random.Range(1, 5);
        displayText.text = testFish.Valuation();
    }
}
